# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `no_proxy_fix` gem.
# Please instead update this file by running `bin/tapioca gem no_proxy_fix`.

module NoProxyFix; end
NoProxyFix::VERSION = T.let(T.unsafe(nil), String)
