# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-reader` gem.
# Please instead update this file by running `bin/tapioca gem tty-reader`.


# pkg:gem/tty-reader#lib/tty/reader/history.rb:5
module TTY; end

# A class responsible for reading character input from STDIN
#
# Used internally to provide key and line reading functionality
#
# @api public
#
# pkg:gem/tty-reader#lib/tty/reader/history.rb:6
class TTY::Reader
  include ::Wisper::Publisher
  extend ::Wisper::Publisher::ClassMethods

  # Initialize a Reader
  #
  # @param [IO] input
  #   the input stream
  # @param [IO] output
  #   the output stream
  # @param [Symbol] interrupt
  #   the way to handle the Ctrl+C key out of :signal, :exit, :noop
  # @param [Hash] env
  #   the environment variables
  # @param [Boolean] track_history
  #   disable line history tracking, true by default
  # @param [Boolean] history_cycle
  #   allow cycling through history, false by default
  # @param [Boolean] history_duplicates
  #   allow duplicate entires, false by default
  # @param [Proc] history_exclude
  #   exclude lines from history, by default all lines are stored
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:79
  def initialize(input: T.unsafe(nil), output: T.unsafe(nil), interrupt: T.unsafe(nil), env: T.unsafe(nil), track_history: T.unsafe(nil), history_cycle: T.unsafe(nil), history_exclude: T.unsafe(nil), history_duplicates: T.unsafe(nil)); end

  # pkg:gem/tty-reader#lib/tty/reader.rb:433
  def add_to_history(line); end

  # Clear display for the current line input
  #
  # Handles clearing input that is longer than the current
  # terminal width which allows copy & pasting long strings.
  #
  # @param [Line] line
  #   the line to display
  # @param [Number] screen_width
  #   the terminal screen width
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:343
  def clear_display(line, screen_width); end

  # pkg:gem/tty-reader#lib/tty/reader.rb:55
  def console; end

  # Count the number of screen lines given line takes up in terminal
  #
  # @param [Integer] line_or_size
  #   the current line or its length
  # @param [Integer] screen_width
  #   the width of terminal screen
  #
  # @return [Integer]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:362
  def count_screen_lines(line_or_size, screen_width = T.unsafe(nil)); end

  # pkg:gem/tty-reader#lib/tty/reader.rb:57
  def cursor; end

  # pkg:gem/tty-reader#lib/tty/reader.rb:50
  def env; end

  # Get input code points
  #
  # @param [Boolean] echo
  #   whether to echo chars back or not, defaults to false
  # @option [Boolean] raw
  #   whenther raw mode is enabled, defaults to true
  # @option [Boolean] nonblock
  #   whether to wait for input or not, defaults to false
  # @param [Array[Integer]] codes
  #   the currently read char code points
  #
  # @return [Array[Integer]]
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:209
  def get_codes(echo: T.unsafe(nil), raw: T.unsafe(nil), nonblock: T.unsafe(nil), codes: T.unsafe(nil)); end

  # pkg:gem/tty-reader#lib/tty/reader.rb:441
  def history_next; end

  # pkg:gem/tty-reader#lib/tty/reader.rb:437
  def history_next?; end

  # pkg:gem/tty-reader#lib/tty/reader.rb:450
  def history_previous; end

  # pkg:gem/tty-reader#lib/tty/reader.rb:446
  def history_previous?; end

  # pkg:gem/tty-reader#lib/tty/reader.rb:46
  def input; end

  # Inspect class name and public attributes
  # @return [String]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:460
  def inspect; end

  # Capture Ctrl+d and Ctrl+z key events
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:428
  def keyctrl_d(*_arg0); end

  # pkg:gem/tty-reader#lib/tty/reader.rb:431
  def keyctrl_z(*_arg0); end

  # pkg:gem/tty-reader#lib/tty/reader.rb:104
  def old_subcribe(listener, options = T.unsafe(nil)); end

  # pkg:gem/tty-reader#lib/tty/reader.rb:48
  def output; end

  # pkg:gem/tty-reader#lib/tty/reader.rb:193
  def read_char(echo: T.unsafe(nil), raw: T.unsafe(nil), nonblock: T.unsafe(nil)); end

  # Read a keypress including invisible multibyte codes and return
  # a character as a string.
  # Nothing is echoed to the console. This call will block for a
  # single keypress, but will not wait for Enter to be pressed.
  #
  # @param [Boolean] echo
  #   whether to echo chars back or not, defaults to false
  # @option [Boolean] raw
  #   whenther raw mode is enabled, defaults to true
  # @option [Boolean] nonblock
  #   whether to wait for input or not, defaults to false
  #
  # @return [String]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:184
  def read_keypress(echo: T.unsafe(nil), raw: T.unsafe(nil), nonblock: T.unsafe(nil)); end

  # Get a single line from STDIN. Each key pressed is echoed
  # back to the shell. The input terminates when enter or
  # return key is pressed.
  #
  # @param [String] prompt
  #   the prompt to display before input
  # @param [String] value
  #   the value to pre-populate line with
  # @param [Boolean] echo
  #   whether to echo chars back or not, defaults to false
  # @option [Boolean] raw
  #   whenther raw mode is enabled, defaults to true
  # @option [Boolean] nonblock
  #   whether to wait for input or not, defaults to false
  #
  # @return [String]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:248
  def read_line(prompt = T.unsafe(nil), value: T.unsafe(nil), echo: T.unsafe(nil), raw: T.unsafe(nil), nonblock: T.unsafe(nil)); end

  # pkg:gem/tty-reader#lib/tty/reader.rb:416
  def read_lines(prompt = T.unsafe(nil), value: T.unsafe(nil), echo: T.unsafe(nil), raw: T.unsafe(nil), nonblock: T.unsafe(nil)); end

  # Read multiple lines and return them in an array.
  # Skip empty lines in the returned lines array.
  # The input gathering is terminated by Ctrl+d or Ctrl+z.
  #
  # @param [String] prompt
  #   the prompt displayed before the input
  # @param [String] value
  #   the value to pre-populate line with
  # @param [Boolean] echo
  #   whether to echo chars back or not, defaults to false
  # @option [Boolean] raw
  #   whenther raw mode is enabled, defaults to true
  # @option [Boolean] nonblock
  #   whether to wait for input or not, defaults to false
  #
  # @yield [String] line
  #
  # @return [Array[String]]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:393
  def read_multiline(prompt = T.unsafe(nil), value: T.unsafe(nil), echo: T.unsafe(nil), raw: T.unsafe(nil), nonblock: T.unsafe(nil)); end

  # Select appropriate console
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:144
  def select_console(input); end

  # Subscribe to receive key events
  #
  # @example
  #   reader.subscribe(MyListener.new)
  #
  # @return [self|yield]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:114
  def subscribe(listener, options = T.unsafe(nil)); end

  # pkg:gem/tty-reader#lib/tty/reader.rb:52
  def track_history; end

  # pkg:gem/tty-reader#lib/tty/reader.rb:53
  def track_history?; end

  # Expose event broadcasting
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:421
  def trigger(event, *args); end

  # Get input in unbuffered mode.
  #
  # @example
  #   unbufferred do
  #     ...
  #   end
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:160
  def unbufferred(&block); end

  # Unsubscribe from receiving key events
  #
  # @example
  #   reader.unsubscribe(my_listener)
  #
  # @return [void]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:132
  def unsubscribe(listener); end

  private

  # Handle input interrupt based on provided value
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:483
  def handle_interrupt; end

  # Publish event
  #
  # @param [String] char
  #   the key pressed
  #
  # @return [nil]
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader.rb:474
  def trigger_key_event(char, line: T.unsafe(nil)); end

  class << self
    # Check if Windowz mode
    #
    # @return [Boolean]
    #
    # @api public
    #
    # pkg:gem/tty-reader#lib/tty/reader.rb:42
    def windows?; end
  end
end

# pkg:gem/tty-reader#lib/tty/reader.rb:26
TTY::Reader::BACKSPACE = T.let(T.unsafe(nil), Integer)

# Key codes
#
# pkg:gem/tty-reader#lib/tty/reader.rb:24
TTY::Reader::CARRIAGE_RETURN = T.let(T.unsafe(nil), Integer)

# pkg:gem/tty-reader#lib/tty/reader/console.rb:10
class TTY::Reader::Console
  # pkg:gem/tty-reader#lib/tty/reader/console.rb:30
  def initialize(input); end

  # Escape codes
  #
  # @return [Array[Integer]]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/console.rb:28
  def escape_codes; end

  # Get a character from console with echo
  #
  # @param [Boolean] echo
  #   whether to echo input back or not, defaults to true
  # @param [Boolean] raw
  #   whether to use raw mode or not, defaults to false
  # @param [Boolean] nonblock
  #   whether to wait for input or not, defaults to false
  #
  # @return [String]
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader/console.rb:49
  def get_char(echo: T.unsafe(nil), raw: T.unsafe(nil), nonblock: T.unsafe(nil)); end

  # Key codes
  #
  # @return [Hash[Symbol]]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/console.rb:21
  def keys; end

  protected

  # pkg:gem/tty-reader#lib/tty/reader/console.rb:65
  def input; end

  # pkg:gem/tty-reader#lib/tty/reader/console.rb:63
  def mode; end
end

# pkg:gem/tty-reader#lib/tty/reader/console.rb:12
TTY::Reader::Console::CSI = T.let(T.unsafe(nil), String)

# pkg:gem/tty-reader#lib/tty/reader/console.rb:11
TTY::Reader::Console::ESC = T.let(T.unsafe(nil), String)

# pkg:gem/tty-reader#lib/tty/reader/console.rb:14
TTY::Reader::Console::TIMEOUT = T.let(T.unsafe(nil), Float)

# pkg:gem/tty-reader#lib/tty/reader.rb:27
TTY::Reader::DELETE = T.let(T.unsafe(nil), Integer)

# Keys that terminate input
#
# pkg:gem/tty-reader#lib/tty/reader.rb:30
TTY::Reader::EXIT_KEYS = T.let(T.unsafe(nil), Array)

# A class responsible for storing a history of all lines entered by
# user when interacting with shell prompt.
#
# @api private
#
# pkg:gem/tty-reader#lib/tty/reader/history.rb:11
class TTY::Reader::History
  include ::Enumerable
  extend ::Forwardable

  # Create a History buffer
  #
  # @param [Integer] max_size
  #   the maximum size for history buffer
  # @param [Boolean] cycle
  #   whether or not the history should cycle, false by default
  # @param [Boolean] duplicates
  #   whether or not to store duplicates, true by default
  # @param [Boolean] exclude
  #   a Proc to exclude items from storing in history
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:66
  def initialize(max_size = T.unsafe(nil), duplicates: T.unsafe(nil), cycle: T.unsafe(nil), exclude: T.unsafe(nil)); end

  # pkg:gem/tty-reader#lib/tty/reader/history.rb:104
  def <<(line); end

  # Return line at the specified index
  #
  # @raise [IndexError] index out of range
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:143
  def [](index); end

  # Empty all history lines
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:166
  def clear; end

  # Decides whether or not to allow cycling through stored lines.
  #
  # @return [Boolean]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:38
  def cycle; end

  # Decides whether or not to allow cycling through stored lines.
  #
  # @return [Boolean]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:38
  def cycle=(_arg0); end

  # Decides wether or not duplicate lines are stored.
  #
  # @return [Boolean]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:45
  def duplicates; end

  # Decides wether or not duplicate lines are stored.
  #
  # @return [Boolean]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:45
  def duplicates=(_arg0); end

  # Iterates over history lines
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:81
  def each(&block); end

  # Dictates which lines are stored.
  #
  # @return [Proc]
  #
  # @public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:52
  def exclude; end

  # Dictates which lines are stored.
  #
  # @return [Proc]
  #
  # @public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:52
  def exclude=(_arg0); end

  # Get current line
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:157
  def get; end

  # The current index
  #
  # @return [Integer]
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:31
  def index; end

  # pkg:gem/tty-reader#lib/tty/reader/history.rb:21
  def inspect(*args, **_arg1, &block); end

  # pkg:gem/tty-reader#lib/tty/reader/history.rb:21
  def length(*args, **_arg1, &block); end

  # Set and retrieve the maximum size of the buffer
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:24
  def max_size; end

  # Set and retrieve the maximum size of the buffer
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:24
  def max_size=(_arg0); end

  # Move the pointer to the next line in the history
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:109
  def next; end

  # pkg:gem/tty-reader#lib/tty/reader/history.rb:119
  def next?; end

  # Move the pointer to the previous line in the history
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:124
  def previous; end

  # pkg:gem/tty-reader#lib/tty/reader/history.rb:134
  def previous?; end

  # Add the last typed line to history buffer
  #
  # @param [String] line
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/history.rb:94
  def push(line); end

  # pkg:gem/tty-reader#lib/tty/reader/history.rb:21
  def size(*args, **_arg1, &block); end

  # pkg:gem/tty-reader#lib/tty/reader/history.rb:21
  def to_s(*args, **_arg1, &block); end
end

# Default exclude
#
# pkg:gem/tty-reader#lib/tty/reader/history.rb:19
TTY::Reader::History::DEFAULT_EXCLUDE = T.let(T.unsafe(nil), Proc)

# Default maximum size
#
# pkg:gem/tty-reader#lib/tty/reader/history.rb:16
TTY::Reader::History::DEFAULT_SIZE = T.let(T.unsafe(nil), Integer)

# Raised when the user hits the interrupt key(Control-C)
#
# @api public
#
# pkg:gem/tty-reader#lib/tty/reader.rb:35
class TTY::Reader::InputInterrupt < ::Interrupt; end

# Responsible for meta-data information about key pressed
#
# @api private
#
# pkg:gem/tty-reader#lib/tty/reader/key_event.rb:10
class TTY::Reader::Key < ::Struct
  # pkg:gem/tty-reader#lib/tty/reader/key_event.rb:11
  def initialize(*_arg0); end
end

# Represents key event emitted during keyboard press
#
# @api public
#
# pkg:gem/tty-reader#lib/tty/reader/key_event.rb:19
class TTY::Reader::KeyEvent < ::Struct
  # Check if key event can be triggered
  #
  # @return [Boolean]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/key_event.rb:53
  def trigger?; end

  class << self
    # Create key event from read input codes
    #
    # @param [Hash[Symbol]] keys
    #   the keys and codes mapping
    # @param [Array[Integer]] codes
    #
    # @return [KeyEvent]
    #
    # @api public
    #
    # pkg:gem/tty-reader#lib/tty/reader/key_event.rb:29
    def from(keys, char, line = T.unsafe(nil)); end
  end
end

# Mapping of escape codes to keys
#
# pkg:gem/tty-reader#lib/tty/reader/keys.rb:6
module TTY::Reader::Keys
  private

  # pkg:gem/tty-reader#lib/tty/reader/keys.rb:7
  def ctrl_keys; end

  # pkg:gem/tty-reader#lib/tty/reader/keys.rb:46
  def keys; end

  # pkg:gem/tty-reader#lib/tty/reader/keys.rb:128
  def win_keys; end

  class << self
    # pkg:gem/tty-reader#lib/tty/reader/keys.rb:44
    def ctrl_keys; end

    # pkg:gem/tty-reader#lib/tty/reader/keys.rb:126
    def keys; end

    # pkg:gem/tty-reader#lib/tty/reader/keys.rb:163
    def win_keys; end
  end
end

# pkg:gem/tty-reader#lib/tty/reader/line.rb:7
class TTY::Reader::Line
  # Create a Line instance
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:40
  def initialize(text = T.unsafe(nil), prompt: T.unsafe(nil)); end

  # Add char and move cursor
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:204
  def <<(char); end

  # Read character
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:179
  def [](i); end

  # Insert characters inside a line. When the lines exceeds
  # maximum length, an extra space is added to accomodate index.
  #
  # @param [Integer] i
  #   the index to insert at
  #
  # @param [String] chars
  #   the characters to insert
  #
  # @example
  #   text = "aaa"
  #   line[5]= "b"
  #   => "aaa  b"
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:146
  def []=(i, chars); end

  # The current cursor position witin the text
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:27
  def cursor; end

  # Remove char from the line at current position
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:212
  def delete(n = T.unsafe(nil)); end

  # Enable edit mode
  #
  # @return [Boolean]
  #
  # @public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:63
  def edit_mode; end

  # Check if line is in edit mode
  #
  # @return [Boolean]
  #
  # @public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:54
  def editing?; end

  # Check if cursor reached end of the line
  #
  # @return [Boolean]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:99
  def end?; end

  # Insert char(s) at cursor position
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:197
  def insert(chars); end

  # pkg:gem/tty-reader#lib/tty/reader/line.rb:233
  def inspect; end

  # Move line position to the left by n chars
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:106
  def left(n = T.unsafe(nil)); end

  # pkg:gem/tty-reader#lib/tty/reader/line.rb:258
  def length; end

  # The line mode
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:31
  def mode; end

  # Move cursor to end position
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:127
  def move_to_end; end

  # Move cursor to beginning position
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:120
  def move_to_start; end

  # The prompt displayed before input
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:35
  def prompt; end

  # Prompt size
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:238
  def prompt_size; end

  # Remove char from the line in front of the cursor
  #
  # @param [Integer] n
  #   the number of chars to remove
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:222
  def remove(n = T.unsafe(nil)); end

  # Replace current line with new text
  #
  # @param [String] text
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:188
  def replace(text); end

  # Enable replace mode
  #
  # @return [Boolean]
  #
  # @public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:81
  def replace_mode; end

  # Check if line is in replace mode
  #
  # @return [Boolean]
  #
  # @public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:72
  def replacing?; end

  # Move line position to the right by n chars
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:113
  def right(n = T.unsafe(nil)); end

  # Full line size with prompt
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:255
  def size; end

  # Check if cursor reached beginning of the line
  #
  # @return [Boolean]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:90
  def start?; end

  # The editable text
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:23
  def text; end

  # Text size
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:248
  def text_size; end

  # Full line with prompt as string
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/line.rb:230
  def to_s; end

  class << self
    # Strip ANSI characters from the text
    #
    # @param [String] text
    #
    # @return [String]
    #
    # @api public
    #
    # pkg:gem/tty-reader#lib/tty/reader/line.rb:17
    def sanitize(text); end
  end
end

# pkg:gem/tty-reader#lib/tty/reader/line.rb:8
TTY::Reader::Line::ANSI_MATCHER = T.let(T.unsafe(nil), Regexp)

# pkg:gem/tty-reader#lib/tty/reader/mode.rb:7
class TTY::Reader::Mode
  # Initialize a Terminal
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/mode.rb:11
  def initialize(input = T.unsafe(nil)); end

  # Echo given block
  #
  # @param [Boolean] is_on
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/mode.rb:20
  def echo(is_on = T.unsafe(nil), &block); end

  # Use raw mode in the given block
  #
  # @param [Boolean] is_on
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/mode.rb:33
  def raw(is_on = T.unsafe(nil), &block); end
end

# pkg:gem/tty-reader#lib/tty/reader.rb:25
TTY::Reader::NEWLINE = T.let(T.unsafe(nil), Integer)

# pkg:gem/tty-reader#lib/tty/reader/version.rb:5
TTY::Reader::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/tty-reader#lib/tty/reader/win_console.rb:7
class TTY::Reader::WinConsole
  # pkg:gem/tty-reader#lib/tty/reader/win_console.rb:26
  def initialize(input); end

  # Escape codes
  #
  # @return [Array[Integer]]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/win_console.rb:24
  def escape_codes; end

  # Get a character from console blocking for input
  #
  # @param [Boolean] echo
  #   whether to echo input back or not, defaults to true
  # @param [Boolean] raw
  #   whether to use raw mode or not, defaults to false
  # @param [Boolean] nonblock
  #   whether to wait for input or not, defaults to false
  #
  # @return [String]
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader/win_console.rb:45
  def get_char(echo: T.unsafe(nil), raw: T.unsafe(nil), nonblock: T.unsafe(nil)); end

  # pkg:gem/tty-reader#lib/tty/reader/win_console.rb:72
  def get_char_blocking; end

  # pkg:gem/tty-reader#lib/tty/reader/win_console.rb:76
  def get_char_echo_blocking; end

  # pkg:gem/tty-reader#lib/tty/reader/win_console.rb:68
  def get_char_echo_non_blocking; end

  # Get the char for last key pressed, or if no keypress return nil
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader/win_console.rb:64
  def get_char_non_blocking; end

  # Check if IO has user input
  #
  # @return [Boolean]
  #
  # @api private
  #
  # pkg:gem/tty-reader#lib/tty/reader/win_console.rb:85
  def input_ready?; end

  # Key codes
  #
  # @return [Hash[Symbol]]
  #
  # @api public
  #
  # pkg:gem/tty-reader#lib/tty/reader/win_console.rb:17
  def keys; end
end

# pkg:gem/tty-reader#lib/tty/reader/win_console.rb:8
TTY::Reader::WinConsole::ESC = T.let(T.unsafe(nil), String)

# pkg:gem/tty-reader#lib/tty/reader/win_console.rb:10
TTY::Reader::WinConsole::EXT_HEX = T.let(T.unsafe(nil), String)

# pkg:gem/tty-reader#lib/tty/reader/win_console.rb:9
TTY::Reader::WinConsole::NUL_HEX = T.let(T.unsafe(nil), String)
